//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public System.DateTime TimeOfCommit { get; set; }
        public int DetailId { get; set; }
        public int ExpertId { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual Expert Expert { get; set; }
    }
}
